### ISSUE TITLE
Faster building

### ISSUE THREAD

**Issue by javl** [jmwohl/sfpc#2]
Not an issue but a tip: you can speed up the build by specifying the amount of cores you have/want to use when calling make. In my case (some random script) `make` takes 18 seconds, while `make -j 4` takes 10 seconds.

Edit: only just realized this repo is three years old so I don't even know if you still use it.

**Comment by jmwohl** [comment]
Ha, yeah I haven't looked at this repo is a long time, but appreciate the info anyway! Good to know about the `-j` flag.
